---
title: "Day 2b Excercises"
author: "BJ"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
# load packages ----
library(tidyverse)

# define funtion ----
eq1 <- function(x) {
  3 * x^2 + 4
}

#create a data frame with range of values from 1 to 100----
my_data_range <- data.frame(x = c(1, 100))

# plot our function as a continuouis curve over our specificed range of values in our df ----

ggplot(data = my_data_range, aes(x = x)) +
  geom_function(fun = eq1)
```


```{r}
# define function ----
eq2 <- function(x) {
  2.4 - 5 * x^3 + 2.1 * x^2
}

# create a data frame with range of values of -50 to 50 ----
my_data_range <- data.frame(x=c(-50, 50))

#plot our fuction as a continuous curve over our specified range of values in our df ----
  
ggplot(data = my_data_range, aes(x = x)) +
    geom_function(fun = eq2) 
```

```{r}
# create funtion C(t)----
ct <- function(t) {
  t^3
}

# find deriv of C(t) ----
dc_dt <- D(expr = expression(t^3), name = "t")
dc_dt

#store derivative as a function ----
dc_dt_fun <- function(t) {
  3 * t^2
}

# df of values ----
my_data_range <- data.frame(t = c(-5, 5))

#plot function ----
ggplot(data = my_data_range, aes(x = t)) +
  geom_function(fun = ct, color = "red") +
  geom_function(fun = dc_dt_fun, color = "blue")
```

```{r}
f_xyz <- expression(2 * x * y - 3 * x^2 * z^3)

# partial with respect x ----
df_dx <- D(expr = f_xyz, name = "x")
df_dx
```





